### ISSUE TITLE
Rework blockquote styles

### ISSUE THREAD

**Issue by fafnirical** [forumone/gesso#145]
Blockquotes currently seem to expect an attribution inside the `<blockquote>` element (see [_starter-kit/_patterns/01-base/02-html-elements/02-text/03-blockquote/_blockquote.scss#L7-L14](https://github.com/forumone/gesso/blob/8.x-2.x/_starter-kit/_patterns/01-base/02-html-elements/02-text/03-blockquote/_blockquote.scss#L7-L14)).

According to the WHATWG specification, the attribution should be placed *outside* the `<blockquote>` element: <https://html.spec.whatwg.org/multipage/grouping-content.html#the-blockquote-element>
> Attribution for the quotation, if any, must be placed outside the blockquote element.

**Comment by coreylafferty** [comment]
There seems to be a LOT of disagreement on this, but generally what I'm finding is that using the cite tag inside a blockquote is now acceptable.  We'll revisit this if the consensus changes or someone points out a definitive answer.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/cite
https://www.w3resource.com/twitter-bootstrap/examples/twitter-bootstrap-blockquote-with-cite-example.php
https://www.w3schools.com/tags/att_blockquote_cite.asp
https://www.w3resource.com/twitter-bootstrap/examples/twitter-bootstrap-blockquote-with-cite-example.html
http://html5doctor.com/cite-and-blockquote-reloaded/
