### ISSUE TITLE
Drop support for Node <8

### ISSUE THREAD

**Issue by fafnirical** [forumone/gesso#156]
Node.js v4 is EOL, and a large number of libraries have stopped supporting it: https://github.com/nodejs/Release#end-of-life-releases

**Comment by fafnirical** [comment]
Node.js v6 goes EOL in April; could be good to upgrade `grunt-sass` to v3 and drop support for Node.js < 8?

**Comment by dcmouyard** [comment]
We’re currently using Node v10 in our 8.x-3.x branch.
