### ISSUE TITLE
grunt-simple-watch is not maintained

### ISSUE THREAD

**Issue by johnbburg** [forumone/gesso#182]
I have a project that ran into this issue: https://github.com/unbalanced/grunt-simple-watch/pull/13. It seems that when using lodash versions > 4.0, the syntax in grunt-simple-watch breaks. The fix is simple, and available in that pull request... which has been sitting there for 2 years un-merged. This is the repo that [the npm package](https://www.npmjs.com/package/grunt-simple-watch) uses.

Now I don't understand why this project in particular ended up  with lodash 4.0+, while most other projects I have using gesso seem to end up with 0.9.2 installed. I believe 0.9.2 is normally used because gesso uses 4.5.0, which declares lodash 0.9.2 as a dependency. Previous versions of grunt-simple-watch do not specify any dependency on a version of lodash, and the project doesn't explicitly set it as a dependency either. Although multiple web-starter generators declare dependencies on lodash > 4.0.

The maintainer of grunt-simple-watch doesn't appear to have been active on GitHub Suffice to say, if we aren't running into this issue already, we will eventually. There does seem to be [a number of forks of grunt-simple-watch available](https://github.com/unbalanced/grunt-simple-watch/network/members) that include this patch. I'm not sure on the best solution here, I'm just raising it as an issue. I suppose we don't need to do anything here, since we should be taken care of by the grunt version, but writing this issue up was a rubber duck moment for me, and I didn't want it to go to waste. So in the spirit of future-proofing gesso, We could:

* Bug the maintainer harder.
* Make our own fork. 
* Explicitly set dependency for lodash < 4.0 in gesso.

**Comment by fafnirical** [comment]
You could probably use https://github.com/e-feit/grunt-simple-watch-legacy?

That said, Grunt itself is barely maintained, based on https://github.com/gruntjs/grunt/graphs/contributors... perhaps it's time to stop using Grunt?

**Comment by coreylafferty** [comment]
After looking into this, we decide to replace simple-watch with chokidar.  This issue is fixed by https://github.com/forumone/gesso/pull/185.  Marking as closed.

**Comment by ve3** [comment]
Can anyone tell about how to use forked repository?
In this case, I used to use https://github.com/unbalanced/grunt-simple-watch and it is not working with new version and come to this topic found that https://github.com/e-feit/grunt-simple-watch-legacy maybe fixed.
But I don't know how to install it?

`npm install e-feit/grunt-simple-watch-legacy --save-dev` not working ( Warning: Task "simple-watch" not found ).
`npm install grunt-simple-watch-legacy --save-dev` not working ( Warning: Task "simple-watch" not found ).
There are no document about this anywhere.

**Comment by fafnirical** [comment]
@ve3 This issue was fixed in Gesso by switching to `grunt-chokidar` in https://github.com/forumone/gesso/pull/185. I'd recommend switching to `grunt-chokidar` as well -- you should be able to apply the changes from the PR to upgrade an existing project
