### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by drewbetts** [forumone/gesso#183]
I initially followed the instructions in the Installation section of the README.md and encountered a number of problems getting Gesso to work. The first bullet says to place the Gesso theme in themes/gesso but I believe it needs to be in themes/contrib/gesso. There was also a version dependency issue between simple-watch and lodash resulting in the error "Warning: grunt.util._.chain(...).pluck is not a function Use --force to continue" when running grunt. There's currently [a question about this issue](https://github.com/forumone/gesso/issues/182).

Using `composer require drupal/gesso` I had it up and running without any problems.

**Comment by coreylafferty** [comment]
@drewbetts Unless there's something specific about your setup to only read themes in a specific subfolder, I would think that /themes/gesso/ would work just fine.  We're looking into the best solution for the simple-watch/lodash dependency issue and should have a fix in shortly.

**Comment by coreylafferty** [comment]
After looking into this, we decided to replace simple-watch with chokidar (https://github.com/forumone/gesso/pull/185).  That should remedy the lodash errors.   We've had no issues using the normal Drupal /themes/[theme name] folder structure with Gesso, but if that is still an issue let me know how I might replicate it and I'll dig into that further.  Marking as closed.
