### ISSUE TITLE
drush gesso --help returns undefined command

### ISSUE THREAD

**Issue by ahimsauzi** [forumone/gesso#184]
Thanks for a great theme, love pattern lab.

When attempting to use drush to create a new theme from gesso, drush gesso --help returns Command "gesso" is not defined. This happens before and after enabling the theme and from any directory (root, web, themes, contrib or gesso). I am using a composer managed drupal 8.6.7 with drush 9.6.0

**Comment by ahimsauzi** [comment]
Looks like example.drush.inc is no longer supported in Drush 9.beta5+.

**Comment by wats958** [comment]
+1. Drush 9 makes the initial theme generation impossible.

I notice that this issue is handled in Gesso 3.x with the included gesso_helper module. It would be nice for support purposes to put this in 2.x as well.

**Comment by kmonahan** [comment]
This fix is in 8.x-3.x.
