### ISSUE TITLE
Remove whitespace in fields

### ISSUE THREAD

**Issue by johnbburg** [forumone/gesso#204]
The rendered fields output a lot of whitespace. There are a few solutions to this outlined in https://drupal.stackexchange.com/questions/231282/how-remove-whitespace-on-field-in-twig.

**Comment by dcmouyard** [comment]
@johnbburg Could you provide a simple test-case that we could setup locally to see this in action?

**Comment by johnbburg** [comment]
Sure, maybe this isn't the best example, but I had a phone field I was trying to render on a node detail page as a linked tel: number, e.g:
```
<tel><a href="tel:{{ content.field_phone }}">{{ content.field_phone }}</a></tel>
```

It would get rendered as 
```
<tel><a href="tel:
    555-555-5555
">
    555-555-5555
</a></tel>
```
I'm not certain if thw whitespace really causes a problem for the function of the link, but it does seem a bit messy. 

This is the change I ended up making to field.html.twig:

```
diff --git a/web/themes/gesso/templates/field/field.html.twig b/web/themes/gesso/templates/field/field.html.twig
index 58f5e527d..3629cf151 100644
--- a/web/themes/gesso/templates/field/field.html.twig
+++ b/web/themes/gesso/templates/field/field.html.twig
@@ -36,8 +36,6 @@
  *
  * @see template_preprocess_field()
  */
-#}
-
-{% for item in items %}
-  {{ item.content }}
-{% endfor %}
+#}{%- for item in items %}
+{{ item.content }}
+{% endfor -%}
\ No newline at end of file
```

**Comment by wats958** [comment]
Things can have whitespace for a reason - Twig debug comments, space between inline-block items (such as a label and field value), code legibility, etc. 

If it causes UI issues for some particular case, you've just shown how to go about fixing it for that case - but I don't think stripping whitespace on unknown output should be the default.

**Comment by johnbburg** [comment]
I agree on not stripping it by default. Whitespace can be intententional. But I don't think the templates themselves should be generating their own.

**Comment by dcmouyard** [comment]
I’m not in favor of stripping out the whitespace in the default field template because it has to be very flexible to accommodate so many different use cases. 

I typically never use the field template on a project, but rather pass field values to the templates I’m using. So in your example @johnbburg I would’ve done this instead:

```
<tel><a href="tel:{{ content.field_phone|field_value }}">{{ content.field_phone|field_value }}</a></tel>
```

**Comment by dcmouyard** [comment]
I forgot to mention that my solution assumes you have the [Twig Field Value](https://www.drupal.org/project/twig_field_value) module installed.
