### ISSUE TITLE
Warning messages after using Drush gesso

### ISSUE THREAD

**Issue by ghost** [forumone/gesso#268]
After troubleshooting that gesso Drush command doesn't work on Drush 8 any more, I updated to Drush 9 (via composer) and that seems to work fine. It created a new theme for me and appears to be working. However, when I ran that command, I received the following three warning messages. Not sure how to troubleshoot those, so I thought I'd open an issue here. Here are the warnings:

```
[warning] include(/app/web/core/themes/bartik/source/_twig-components/functions/add_attributes.function.drupal.php): failed to open stream: No such file or directory GessoExtensionLoader.php:31
[warning] include(): Failed opening '/app/web/core/themes/bartik/source/_twig-components/functions/add_attributes.function.drupal.php' for inclusion (include_path='/app/vendor/pear/archive_tar:/app/vendor/pear/console_getopt:/app/vendor/pear/pear-core-minimal/src:/app/vendor/pear/pear_exception:.:/usr/local/lib/php') GessoExtensionLoader.php:31
[warning] file_get_contents(/app/web/themes/siduri/js/scripts.js): failed to open stream: No such file or directory GessoHelperCommands.php:179
```

**Comment by kmonahan** [comment]
Saw the same error when running a non-Gesso-specific drush command as well.

**Comment by kmonahan** [comment]
Issue seems to occur when the Gesso Helper module is enabled but Gesso or a custom theme based on Gesso is not the default theme. Can reproduce this on a fresh Drupal install by enabling Gesso Helper while the default theme is Bartik and running any drush command (even drush cr).

**Comment by ghost** [comment]
I can confirm this works, thank you!
