### ISSUE TITLE
Remove site container layout component

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#287]
This is one of the first components I remove whenever I start a new project. It has no related styles by default, so it’s just another div wrapper around everything.

Thoughts?

**Comment by coreylafferty** [comment]
I find this useful when you need a wrapper around everything (e.g., when the site itself has a max-width like http://countyhealthrankings.org).  I don't think it hurts anything being there if you don't need it, but I don't feel super strongly about this either way.
