### ISSUE TITLE
Alignments in CKEditor / Core

### ISSUE THREAD

**Issue by ghost** [forumone/gesso#296]
Hi there, when using the CKEditor from core, I set an alignment - say right aligned. Which gives a class of "text-align-right" to the paragraph. It shows it working in the CKEditor. When I then load this on the front end, it's not right aligned. I found that the system align module (/core/themes/stable/css/system/components/align.module.css) is not loading on the front end. So, I added it to the gesso-sub-theme I created and it worked fine.

My question is - is this by design so that we have to create our own classes in the components for alignments (or other system/CKEditor styles) or, should we include them in the libraries.yml out of the gate?

Just curious what the base thought was is all. Thanks!

**Comment by dcmouyard** [comment]
We left it out by design so that we only include the CSS we need. You outlined the two different approaches we usually take:

1. Add our own alignment utility classes and update CKEditor plugin
2. Add `align.module.css` to the `libraries.yml` file.

**Comment by ghost** [comment]
Perfect, thank you!
