### ISSUE TITLE
collapse.js and dropbutton.js no longer work

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#314]
These JavaScript files (found in `js/overrides/`) no longer work since they require jQuery to be loaded on the page.

**Comment by kmonahan** [comment]
@dcmouyard, what are we using those for? You can add jQuery to an individual project by listing it as a dependency for the global library, but I'm wondering if these scripts should ultimately be refactored.

**Comment by dcmouyard** [comment]
@kmonahan I believe these are used to override Drupal core’s collapse and dropbutton JS to match the markup we’re using. I assumed Drupal would mark those scripts as dependent on jQuery, so jQuery would automatically get added if they’re added to a page, but that’s not currently happening.

I’d be open to refactoring them to not use jQuery.

**Comment by kmonahan** [comment]
jQuery is still listed as a dependency for the core/drupal.dropbutton library and the core/drupal.collapse library, and when I attach one of those libraries to a template, I'm seeing both jQuery and the override script added and in the correct order (jQuery loading first). @dcmouyard, can you provide some more details about where you were encountering those scripts being called without jQuery on the page?

**Comment by dcmouyard** [comment]
Hmm, I can’t reproduce this either. I should’ve listed where this was happening. It’s currently working for me in Pattern Lab and Drupal.
