### ISSUE TITLE
Vulnerabilities when running npm install

### ISSUE THREAD

**Issue by ebremner17** [forumone/gesso#325]
When running npm install, using nodejs 13.7.0 or 12.14.6 and gulp 4.0.2, there are 46 vulnerabilities (5 low, 3 moderate and 38 high).  See attached file for the fixes suggest form npm audit.

Here is the error message when running npm install:
found 46 vulnerabilities (5 low, 3 moderate, 38 high) in 32982 scanned packages
  run `npm audit fix` to fix 41 of them.
  1 vulnerability requires semver-major dependency updates.
  4 vulnerabilities require manual review. See the full report for details.

[npm_audit.txt](https://github.com/forumone/gesso/files/4135675/npm_audit.txt)

**Comment by ghost** [comment]
Following. I got the same with the last build I used as well. I'm not as familiar with NPM so I didn't know if I could/should/know how to fix the last 5.

**Comment by kmonahan** [comment]
This was addressed in https://github.com/forumone/gesso/pull/326. As noted in the PR, you'll still see a few vulnerabilities that trace back to @pattern-lab/core, which needs to update some of its dependencies for those to be resolved.

A word of caution if you apply the work in 326 to a site that's already underway: that PR also gets Prettier up and running on scss files again, which means you'll probably start seeing linting errors you never saw before. You can either fix them (many text editors have Prettier integrations that'll do the work for you) or set the `prettier/prettier` rule to false in `.stylelintrc.yml`.
