### ISSUE TITLE
[8.x-1.x] Template docblocks

### ISSUE THREAD

**Issue by fafnirical** [forumone/gesso#37]
Discussion from https://github.com/forumone/gesso/pull/36#pullrequestreview-4128251

We started removing documentation from template docblocks to match the template files for Drupal 7. Should we revisit that approach for Drupal 8?

**Comment by dcmouyard** [comment]
I lean towards not having the verbose docblocks in our template files.

**Comment by fafnirical** [comment]
I think we should have them, per the coding standards: https://www.drupal.org/docs/develop/coding-standards/twig-coding-standards#docblock

**Comment by blakethomp** [comment]
I second @fafnirical

**Comment by chazchumley** [comment]
I say we remove them since PL is our canonical source for markup going forward.  No need to mix Platform specific comments in PL

**Comment by chazchumley** [comment]
Going to close this issue since we are documenting both the PL and Drupal templates now with docblocks
