### ISSUE TITLE
Media selector not working

### ISSUE THREAD

**Issue by dhruveonmars** [forumone/gesso#413]
After creating a field of media type, that allows Images. The media selector in grid view doesn't work, and requires changing to the table view to work.

For eg, uploading an image works, however selecting it doesn't work while in Grid View. 
To select any image, whether it's one that's been uploaded or whether it's one that already exists, requires swapping to the Table view.

I've checked the php logs, drupal logs and console, but can't seem to see anything related to this.

Any help with this is really appreciated

**Comment by coreylafferty** [comment]
@dhruveonmars I tracked this down to one of the view templates not properly adding the attributes for each view-row.  If you make the change shown in this PR, Grid View should work as expected.  Thanks for catching this!

https://github.com/forumone/gesso/pull/416/files
