### ISSUE TITLE
Drush function not loading

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#425]
After enabling the `gesso_helper` module, I’m not able to use the drush gesso function. I tried clearing the cache via `drush cr` and `drush cache-clear drush`.

```
The drush command 'gesso' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.
```

**Comment by kmonahan** [comment]
@dcmouyard , what version of Drush are you using? I think you need 9 or higher.
