### ISSUE TITLE
Make sure mobile menu JS doesn’t duplicate IDs

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#443]
When JS copies the main menu into the mobile menu, make sure it doesn’t copy over IDs and certain ARIA attributes that shouldn’t be repeated (aria-controls, aria-owns, etc.)

**Comment by kmonahan** [comment]
@dcmouyard Fixed this as part of the menu work in Gesso 5. Good to close?

**Comment by dcmouyard** [comment]
Yep! Fixed in the `5.x` branch.
