### ISSUE TITLE
SVG mixin doesn't work in IE 11 (Windows 10)

### ISSUE THREAD

**Issue by lrobeson** [forumone/gesso#49]
SVG file doesn't work in IE 11 with the SVG mixin, but it works if just using `background-image: url('../images/bg/logo.svg');`.

![Windows 10 IE 11 no mixin](https://cl.ly/1X333z3B0B0z/Image%202016-12-06%20at%2010.52.52%20AM.png)

Here's the SVG used in the above example (Github doesn't support SVG attachments): http://hastebin.com/fadimiyuzo.scala.

**Comment by dcmouyard** [comment]
I did some testing with the svg-background mixin, and it works in IE11 as long as the SVG has a height & width attribute defined. More info here: https://thatemil.com/blog/2015/03/15/sizing-svg-background-images-in-internet-explorer/

**Comment by lrobeson** [comment]
Possibly related? forumone/web-starter/issues/262
