### ISSUE TITLE
[Gesso 5] Setup Github actions to update the demo site

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso#511]
Setup Github actions to update the demo site at https://forumone.github.io/gesso/ whenever new code is merged into the 5.x branch.

**Comment by coreylafferty** [comment]
@kmonahan I merged in #519. Afterwards I got an email alert that the build had failed. Let me know if you didn't receive the same or have questions.

**Comment by kmonahan** [comment]
I did not get the same email, but I'll take a look. This one may take a couple rounds of deploys before it's up and running.

**Comment by kmonahan** [comment]
I think https://github.com/forumone/gesso/pull/522 fixed it, but let's wait after the next merge to ensure the build runs successfully before closing.

**Comment by dcmouyard** [comment]
The builds are running successfully!
