### ISSUE TITLE
Change name of gesso_image_path variable

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#512]
What do folks think about renaming the `gesso_image_path` variable? Perhaps to `theme_image_path`?

**Comment by coreylafferty** [comment]
@dcmouyard I think the original thought was that there might be a Drupal setting somewhere named that, so we kept it more specific.  But if we're sure there isn't/won't be a conflict, I'm fine with that change.

**Comment by dcmouyard** [comment]
For what it’s worth, this approached worked really well on NRDC. I didn’t notice any real drawbacks.

**Comment by dcmouyard** [comment]
Fixed in #521
