### ISSUE TITLE
[Gesso 5] Drush command to copy theme

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#513]
The `drush gesso` command misses the following changes:
- References to theme settings in `includes/html.inc` (ex: `$attachments['#attached']['drupalSettings']['gesso']['backToTopSmoothScroll']`)
- Filenames in `config` directory (ex: `config/schema/gesso.schema.yml`)
- machine names in all files in `config` directory (ex: `theme: gesso`)

**Comment by kmonahan** [comment]
@dcmouyard `References to theme settings in includes/html.inc` should stay as is. (I actually did a bunch of work to make sure those were _not_ changed).

**Comment by kmonahan** [comment]
The others make sense: those files were added after the drush command was created, so they need to be added to the find-and-replace.
