### ISSUE TITLE
Upgrade from 8.x-1.x

### ISSUE THREAD

**Issue by alexshypilov** [forumone/gesso#520]
Is there a way to make a quick upgrade from 8.x-1.x to 8.x-4.x?

**Comment by coreylafferty** [comment]
@alexshypilov I wish I had a better answer, but unfortunately, no. Gesso is meant as a starter theme, not a base theme -- so once you start customizing it, it's not meant to be upgraded. Exceptions to that might be small bug fixes or feature editions within a major release branch, but you would make those changes manually by looking at individual pull requests and replicating them in your custom theme as needed.  

The differences between 1.x and 4.x are so great, I can't really imagine any way to upgrade other than installing 4.x fresh and retheming your site from scratch (perhaps referencing your old theme's custom markup and CSS as a guide). If you were to consider doing something like that, you might want to wait a little while longer -- we expect 5.x to release in December, which replaces Pattern Lab with Storybook, amongst other changes.

**Comment by alexshypilov** [comment]
@coreylafferty thank you for the answer
