### ISSUE TITLE
h1 in site name?

### ISSUE THREAD

**Issue by johnbburg** [forumone/gesso#574]
I ran an SEO scan (using https://www.seobility.net/) on a site, and it raised the issue of multiple h1 tags appearing on the page. One source being the site name
https://github.com/forumone/gesso/blob/5.x/source/03-components/site-name/site-name.twig#L12

Since page titles are also rendered with h1s, this seems redundant. Is there a reason to have the site names as an h1?  This may not really be much of an issue, since Google themselves have confirmed that it's not https://youtu.be/zyqJJXWk0gk, Of course Google isn't the only search engine out there, and this may impact others. What are people's thoughts?

**Comment by dcmouyard** [comment]
Technically, having more than one h1 on a page shouldn’t be an SEO or accessibility issue per the HTML spec, as long as they’re nested correctly in sectioning elements. That said, no browsers or assistive technologies implement the outline algorithm correctly, so there should only be one h1 on a page. 

I think that h1 should definitely be the page title, and not the site name. I’ve never used the default Gesso site name component as-is on a project, so I’ve never run into this problem. but I think we should update the default markup in Gesso.

**Comment by coreylafferty** [comment]
closed by #577.
