### ISSUE TITLE
Prep for CKEditor 5

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso#615]
With CKEditor 5, the editor is no longer loaded in an iframe. Per https://www.drupal.org/node/3259165, we need to scope any editor styles CSS that might conflict with the admin theme (such as bare heading tags) with `.ck-content`. Will require changes to our current editor-styles.scss file and updates to the info.yml file.

**Comment by dcmouyard** [comment]
Until CKEditor becomes the default WYSIWYG editor in Drupal 10, our PR should support both CKEditor 4 and CKEditor 5.
