### ISSUE TITLE
Remove `Fibers` / Upgrade Gesso for Node 16

### ISSUE THREAD

**Issue by rjensen26** [forumone/gesso#626]
According to the https://www.npmjs.com/package/fibers, this will not work for `node 16`

> Update [April 13th, 2021] -- Fibers is not compatible with nodejs v16.0.0 or later. Unfortunately, v8 commit [dacc2fee0f](https://github.com/v8/v8/commit/dacc2fee0f815823782a7e432c79c2a7767a4765) is a breaking change and workarounds are non-trivial.

**Comment by coreylafferty** [comment]
This has been addressed in the latest release (5.1.3).
