### ISSUE TITLE
[Dropdown Menu] Mousing off second-level submenu does not close parent menu

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso#663]
On https://forumone.github.io/gesso/?path=/story/components-menu-dropdown-menu--dropdown-menu, hover over "About" and then "Submenu item one" to open the second-level submenu. Continue dragging the mouse to the right until it's off the menu entirely.

**Expected**: The menu closes once it's no longer being hovered over.
**Observed**: Only the second-level submenu closes. The first-level menu remains visible until you hover on it and off it again.

**Comment by jbwagner** [comment]
#664 opened for this one
