### ISSUE TITLE
Create a modal component for Gesso

### ISSUE THREAD

**Issue by coreylafferty** [forumone/gesso#683]

**Comment by tomealter** [comment]
Going to use `<dialog>` now that it has better browser support.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#examples

**Comment by tomealter** [comment]
AC:
- Use `<dialog>` element and available methods
- Close modal on escape press
- If modal contains remote media (`<iframe>`), reset src on close
- Focus first tabbable element on open
- Trap focus inside modal while open
- Close modal on overlay click (outside inner content)
- Allow scrolling inside modal

Possible Options
- Dark vs. light theme
- Overlay: true/false

**Comment by dcmouyard** [comment]
Just saw that USWDS has implemented this: https://designsystem.digital.gov/components/modal/

**Comment by ShawnJW** [comment]
The USWDS modal is not working for me when logged into the admin area, but works correctly when logged out.  Disabling core/misc/ajax.js temporarily makes the issue go away, not sure if it's a theme issue with Gesso, or a Drupal issue unfortunately.

**Comment by tomealter** [comment]
PR: https://github.com/forumone/gesso/pull/855
