### ISSUE TITLE
For inline images added in CKEditor 5, alignment does not work if there is a caption

### ISSUE THREAD

**Issue by jbwagner** [forumone/gesso#704]
Steps to repro:

- In a WYSIWYG field on CKEditor 5, add an image
- choose align right, save
- the image is floated right
- edit page again, giving that aligned image a caption
- image no longer is floated, just block styled
- remove caption
- image is floated right again

In what research I could get on this, it seems like the `<drupal-media>` element has the data-align attribute when I view source, but that attribute is getting removed somewhere along the render path.

I can workaround this by either using the default template, or merging the existing `classes` string with the newly created `classes` inside the `filter-caption.html.twig` template.

**Comment by jbwagner** [comment]
One thing I forgot to add above, the site I'm working on is on Drupal 9.5 and CKEditor 5 with Gesso 5.1.4. Not sure if this is fixed by upgrading to Drupal 10 and Gesso 5.2.x, but the template seems to be the same in either version of Gesso. So it's either a Drupal bug/poor interaction with Gesso, or a CKEditor 5 bug/interaction with Gesso.

**Comment by jbwagner** [comment]
We did some more research, and it appears the data attributes are being removed in FilterAlign (https://git.drupalcode.org/project/drupal/-/blob/9.5.9/core/modules/filter/src/Plugin/Filter/FilterAlign.php#L33) within Drupal core. It feels like this is a recent change, since our templates rely on this particular attribute being present in multiple circumstances. The Filter is definitely running before our preprocess and therefore the attributes are gone. I don't know if there's been some recent change to the filter or weights or ordering, but it's definitely way in core.

**Comment by jbwagner** [comment]
The attributes (like data-view-mode) are also getting removed, just FYI. Whatever solution we come up with should either work for or account for those as well.

**Comment by dcmouyard** [comment]
@jbwagner Are you just adding images, or using the Media module?

**Comment by dcmouyard** [comment]
@jbwagner How are you aligning images?

Via the text-alignment button?
![Screenshot 2023-06-30 at 1 00 53 PM](https://github.com/forumone/gesso/assets/135259/50bc189b-1b62-4bf9-ace9-bee475b98e14)

Or via the image popup menu?
![Screenshot 2023-06-30 at 1 01 18 PM](https://github.com/forumone/gesso/assets/135259/9f62f46a-bc56-494e-a557-e76af83a7269)

**Comment by dcmouyard** [comment]
I can reproduce this issue in Drupal 9.5.4 and Gesso 5.2.1 using the out-of-the-box image embed and alignment options.

**Comment by jbwagner** [comment]
@dcmouyard I was using the image popup window to align. It should be just a normal media embed, but I'd be curious if other methods have the same issue.
