### ISSUE TITLE
Consider removing role="presentation" on ... in pager

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso#718]
A couple of issues with our default markup came up on a recent project.

Corinne S. did some screenreader testing and found that while having the role does successfully remove the ellipsis from the accessibility tree and causes the screenreader to read the ellipsis as not part of the pager list, it also messes up the numbering.
> The link for “Page 3” is labeled 4 of 6, but when you advance to the ellipsis, it’s labeled 5 of 7. The final page is labeled 5 of 6, and the link for “next page” doesn’t get a list item number. 

Secondly, SiteImprove flags the role attribute on a list item as incorrect. Based on both Corinne S.'s and my research, we think this is a false report from SiteImprove (list items can have a role), but it's still worth noting because it takes additional dev and QA time to sort out false positives and communicate that to the client.

On the other hand, it looks like Olivero's default pager.html.twig template does still keep the role="presentation". So some additional testing and research might be warranted before we decide how to update.

**Comment by dcmouyard** [comment]
I believe I found a good solution borrowed from USWDS: on ellipsis list items, replace `role="presentation"` with `aria-label="ellipsis indicating non-visible pages"`.
