### ISSUE TITLE
Refactor Menu Local Task templates to better adhere to Drupal best practices

### ISSUE THREAD

**Issue by azinck** [forumone/gesso#728]
Currently the approach to rendering local tasks as seen in `menu-local-tasks.html.twig` doesn't properly adhere to Drupal best practices.  It pulls data out of the render array for the individual (child) local tasks and handles the rendering of them directly in the template.  

The current approach is what caused this fix to have to be committed since the templates never checked if the user was supposed to see the tasks before rendering them: https://github.com/forumone/gesso/commit/5650f36a7cee4fe9977927a72df0f06cf6a08b6f

The current approach also has a few more downsides:
* Task weight isn't honored so the tasks are displayed in a "random" order.
* Cache metadata won't be properly bubbled up from the child render array.
* Other elements attached to the render array (custom classes, js/css libraries, etc) won't be honored.

The correct approach would be to ensure the child-specific (per-link) markup is rendered in `menu-local-task.html.twig` and then just output `primary` or `secondary` in menu-local-tasks.html.twig, allowing the rendering engine to render them properly.

**Comment by dcmouyard** [comment]
I took a stab at this and got everything working in Drupal, but ran into an issue in Storybook in getting data to the new button-group-item twig template. WIP is in branch `728-refactor-local-task-menu`.
