### ISSUE TITLE
Update React Webpack with custom fonts

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso#757]
Currently, the webpack React config emits its own copy of any font files uploaded to the theme. Better would be for it to reference the existing font files output by the theme build.

**Comment by dcmouyard** [comment]
I get a white screen when trying to view Storybook with the message:

```Cannot GET /```

**Comment by kmonahan** [comment]
@dcmouyard Hm, that sounds like an issue with your local. Do you see anything if you run `ddev storybook monit`?

**Comment by dcmouyard** [comment]
My previous error went away after I restarted Docker Desktop.
