### ISSUE TITLE
Field Configuration Discussion [Drupal]

### ISSUE THREAD

**Issue by johnbburg** [forumone/gesso#790]
I'd like to discuss the feasibility of making greater use of configurable formatters that can provide more options to site builders.  A module like [Fences](https://www.drupal.org/project/fences) allow site builders to define a field tag in the display configuration. But the current Gesso theme's [field template](https://github.com/forumone/gesso/blob/5.x/templates/field/field.html.twig) is incompatible with the field template required by that module. Example of [Fences field template](https://git.drupalcode.org/project/fences/-/blob/3.x/templates/field.html.twig?ref_type=heads).

Forum One's approach to site building in D7 perhaps leaned a bit too heavily in doing everything in configuration. But I feel like we've over-corrected a bit since 8, making heavy use of twig templates, and needing to create a new one if we need any level of customization, when there are options to just set things in the field's display configuration.   

Is there a way we can set up Gesso to be compatible with a module like Fences? Is there any interest in that from FEDs? 

Edit: I will note that the [Text Field Formatter](https://www.drupal.org/project/text_field_formatter) module seems to work in this use case, as it's not dependent on using it's own field template.

**Comment by dcmouyard** [comment]
I’ve got to admit, thinking about how much we did view mode configuration in D7 brings back some painful memories. Handling things directly in templates has made my life so much easier.

That said, we should be able to give folks the option to use configuration where necessary. I believe the current field templates work with all configuration in Drupal core. I’m going to look into the Fences module (can’t believe it’s still around in D10) to see what it would take to make our templates compatible.

**Comment by dcmouyard** [comment]
How’s this for a potential solution? We create a new `field--fences.html.twig` template that is compatible with the Fences module. Projects that install & enable the Fences module can then either replace `field.html.twig` with `field--fences.html.twig` or only use it on a case-by-case basis by extending `field--fences.html.twig` in specific field templates.

I’m hesitant to update the default `field.html.twig` template since we’d then have to create a dependency on the Fences module. Thoughts?

**Comment by johnbburg** [comment]
I'm developing new painful memories now with the need to create a new twig file for every little thing I do. I think the field--fences idea is great, though it seems like we would run into the same issue of the complexity of making a template comptible with gesso. 

A lot of the issues I'm running into surround three basic use cases. 1, removing the title from non-page view modes. I think newer Gesso has addressed this? 2, inserting links around a "Formatted title" field I've created to allow me to arrange some sort of "title" like field in view modes. And 3, which this issue is directly addressing, customizing the markup around individual fields.

**Comment by dcmouyard** [comment]
While working on this, I realized we could update our Field component to be compatible with Fences _without_ needing a separate `field--fences.html.twig` template.

**Comment by johnbburg** [comment]
Since I posted a review on the PR at https://github.com/forumone/gesso/pull/797, I've realized that the delimiter is determined by the "separator" and "show_separator" values. But these are solely determined by the options from the passed twig template. It would be nice if these could be configurable as well, or, if that just defaulted to nothing instead of the comma and space, which is more in line with core's behavior.

**Comment by johnbburg** [comment]
For example, here is a mini module I just whipped up that can make those values configurable from the interface, based on the code in fences:

```
use Drupal\Component\Render\FormattableMarkup;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FormatterInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_field_formatter_third_party_settings_form().
 */
function f1_field_separator_field_formatter_third_party_settings_form(FormatterInterface $plugin, FieldDefinitionInterface $field_definition, $view_mode, $form, FormStateInterface $form_state) {
  if (!(\Drupal::currentUser()->hasPermission('edit fences formatter settings'))) {
    // The current user doesn't have permission to edit fences formatter
    // settings:
    return;
  }

  $settings['f1_field_separator'] = [];

  $settings['f1_field_separator'] = [
    '#type' => 'details',
    '#title' => t('F1 Field Separator'),
  ];

  $settings['f1_field_separator']['show_separator'] = [
    '#title' => t('Show Separator'),
    '#type' => 'checkbox',
    '#default_value' => $plugin->getThirdPartySetting('f1_field_separator', 'show_separator', false),
  ];

  $settings['f1_field_separator']['separator'] = [
    '#title' => t('Separator'),
    '#type' => 'textfield',
    '#default_value' => $plugin->getThirdPartySetting('f1_field_separator', 'separator'),
    // Remove default maxlength of 128:
    '#maxlength' => NULL,
  ];

  return $settings['f1_field_separator'];
}

/**
 * Implememts hook_preprocess_field().
 */
function f1_field_separator_preprocess_field(&$vars) {
  // Default to showing all markup.
  $vars['show_separator'] = FALSE;
  $vars['separator'] = ', ';

  if (isset($vars['element']['#third_party_settings']['f1_field_separator'])) {
    $f1_field_separator_config = $vars['element']['#third_party_settings']['f1_field_separator'];

    $vars['show_separator'] = $f1_field_separator_config['show_separator'];
    $vars['separator'] = new FormattableMarkup($f1_field_separator_config['separator'], []);
  }
}
```

Maybe we can make this a sub-module to gesso? Or implement right in gesso's field.inc?

Edit: this is definitely not backwards compatible. I tried plugging in the new field template into an older implementation, and it does lead to a lot of changes in the markup, and seemingly adding field labels. 

Edit 2:  Updated the `$vars['separator']` value to use `FormattableMarkup` so it can contain, and render HTML.

**Comment by coreylafferty** [comment]
Fixed by https://github.com/forumone/gesso/pull/797
