### ISSUE TITLE
Adding template for inline hero to implement with Drupal Project

### ISSUE THREAD

**Issue by gbeezus** [forumone/gesso#793]
Implementing the hero component on Drupal Project and I'm wondering if a template would be welcomed here.

Here is the related [issue](https://github.com/forumone/drupal-project/issues/97) in Drupal Project and the corresponding [PR](https://github.com/forumone/drupal-project/pull/103).

Here is a [demo](https://f1-dev-f1-dp-demo.pantheonsite.io/example-page). Scroll to the bottom.

Beyond providing a template I also update a rule for the inline hero to include the use of `figure` since that is what is used out of the box with a media entity/image file type. Both the template and the tweak to the style can be viewed in this [commit](https://github.com/forumone/drupal-project/commit/713d972a06856af0e99449748ec2ed36a8ca919c). I am happy to create PR here if this change is welcomed.

**Comment by dcmouyard** [comment]
@gbeezus Definitely create a PR here!
