### ISSUE TITLE
Node attributes are ignored, and "role" attribute is redundant

### ISSUE THREAD

**Issue by johnbburg** [forumone/gesso#795]
This two issues. 

In Gesso's node templates, we go through the effort of combining our classes with the `attributes` variable passed to the theme template, but then we just ignore the attributes variable, as it's not passed to the included template. A couple of examples

[Full display for node](https://github.com/forumone/gesso/blob/5.x/templates/content/node--full.html.twig#L75)

[Teaser display](https://github.com/forumone/gesso/blob/5.x/templates/content/node--teaser.html.twig#L75)

I propose we pass the attributes variable to the component template, and begin using that in the article tag, like core does. Is there any reason not to do this? I believe the fact that we do not do this currently interferes with things like contextual links.

Second issue, which is really a follow up to the first: 

We are still using a `role="article"` attribute hard-coded on the `article` tag within the [component template](https://github.com/forumone/gesso/blob/5.x/source/03-components/teaser/teaser.twig#L13).

Drupal core actually [removed this](https://www.drupal.org/project/drupal/issues/3117230) from their templates in 10.1. Because the default "role" value for "article" tags is "article". For supporting documentation, see the the "Implicit ARIA role" in Mozilla's [HTML documenation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article). I propose we remove this, which would effectively happen anyway from the first proposal I made.

**Comment by dcmouyard** [comment]
> but then we just ignore the attributes variable, as it's not passed to the included template.

The attributes variable _does_ get sent to the Storybook article and teaser templates. Although it’s not explicitly set in code, the variable still gets passed on. I’ll create a PR to make sure we explicitly add in the code so it’s more obvious.

I’ll also remove the hard-coded role attribute in the article template.

**Comment by johnbburg** [comment]
I've since figured out that the contextual links are inserted via the `{{ title_prefix }}` value, so we may also want to make sure that gets passed and used. However, I think using that core attributes variable is still important as there may be selectors that use that.

**Comment by dcmouyard** [comment]
I believe we’re already outputting `{{ title_prefix }}` where appropriate. Are there any cases where this is missing?

**Comment by johnbburg** [comment]
Possibly, the nature of my work tends to put older versions of gesso in front of me.

**Comment by coreylafferty** [comment]
Fixed in #796
