### ISSUE TITLE
USWDS Government Banner

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#802]
We ported over the [USWDS Government Banner](https://designsystem.digital.gov/components/banner/) to Gesso on a project that needed it, but we weren’t using the [Gesso USWDS theme](https://github.com/forumone/gesso-uswds). Would it be beneficial to add that component here? Folks could easily remove it on projects that don’t need it.

**Comment by kmonahan** [comment]
My initial thought here is no. Projects that need the government banner will generally use GUS or some other USWDS-based theme, and the one where it was ported over was enough of an edge case that it's not something we need to account for in Gesso. But definitely open to discussion if others have seen this come up.

**Comment by coreylafferty** [comment]
Agree with KJ on this one.  Closing.
