### ISSUE TITLE
SUPPORT svgs in css with ::after pseudo-element and content: url('')? 

### ISSUE THREAD

**Issue by emb03** [forumone/gesso#815]
I am following this README:

> # Images

> Gesso comes with a task that will automatically create a sprite from SVG images
located in `source/images/_sprite-source-files/`. The generated SVG sprite
(`dist/images/sprite.artifact.svg`) is used in the icon component in Storybook.

> The filename of the SVG image in `source/images/_sprite-source-files/` will
become the id used for its `<symbol>` in `dist/images/sprite.artifact.svg`.

> Images used in CSS will be inlined or copied to a `dist/images/backgrounds`
directory by Webpack, depending on the size of the file. The image path should
be `../images/backgrounds/[whatever]`, regardless of the number of
subdirectories your SCSS file is nested within. The `svg-background` mixin can
be used to create a background image URL using an SVG file.

My custom svg file is being saved successfully to the artifact.svg file

In my scss I have:
`content: url('../images/backgrounds/right-arrow-brown');`
but I get this error:

> Failed to compile.
> Module not found: Can't resolve '../images/backgrounds/right-arrow-brown' in '/Users/name/sites/vanilla-drupal/web/themes/custom/guswds_name/source/04-components/figma-card'
node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[18].use[2]!./source/04-components/figma-card/figma-card.scss

I am able to use this and it works so I think it's an issue with url path....
`&:after {
content: '→';
}`

**Comment by dcmouyard** [comment]
The SVG sprite isn’t used for CSS background images or content, it’s used for inline SVG elements (e.g., [Icon component](https://forumone.github.io/gesso/?path=/story/components-icon--icon)).

If you want to use an SVG in CSS, just add the SVG file to `source/images/backgrounds/` and use the `svg-background()` mixin. Here’s an example: https://github.com/forumone/gesso/blob/5.x/source/03-components/message/message.scss#L63

If you _really_ need to use the SVG sprite in CSS, we’ll probably have to update `webpack.common.js`.
