### ISSUE TITLE
Cache bust image backgrounds

### ISSUE THREAD

**Issue by johnbburg** [forumone/gesso#894]
Here is a use case that caused me a bit of annoyance during a big deploy. I replaced the images that are used as icons/backgrounds through the `svg-background()` mixin.  Generally, CDNs have fairly long cache lifetimes for static assets, like images. So replacing these can be difficult, and is not easily done via cache clear, as user's browsers will continue holding onto these until the Expires date in the header, which could be several days - weeks.

I propose that we append a parameter to any generated URLs, like in `svg-background`, from the `unique_id()` function.  e.g.

```
@mixin svg-background($image-name, $image-location: 'images/backgrounds/') {
  $url: $image-location + $image-name + '.svg?' + unique_id();
  background-image: url($url);
}
```
See: 
https://code-road.medium.com/sass-unique-id-for-cache-busting-your-css-fbb58d126d2d
https://sass-lang.com/documentation/modules/string/#unique-id

Are there any other image URLs generated like this that could also benefit?

**Comment by kmonahan** [comment]
@johnbburg Was the site where this occurred using the current version of Gesso 5? I would have thought Webpack handled this for us, but I could be wrong!

**Comment by johnbburg** [comment]
@kmonahan , This was on Gesso 2. I checked a newer site, and I do see it referencing images in the /dist directory with a hash in the name. So it looks like this is a non-issue for Gesso 5. It's still good to know for our older sites, and I might propose to the support team that we implement this on any older versions of Gesso out there in the wild.
